FROM node:lts-alpine

# make the 'app' folder the current working directory
WORKDIR /server

# copy both 'package.json' and 'package-lock.json' (if available)
COPY /package*.json ./


RUN npm install --force

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY / .


EXPOSE 8008
CMD [ "node", "server.js"]